---
- name: Installing and start service of docker and create container from image
  hosts: all
  become: true
  remote_user: ec2-user
  tasks:
     - name: install a package
       yum:
         name: docker
         state: present
     - name: start service
       service:
         name: docker
         state: started

     - command: docker info
       register: hello
     
     - debug:
          var: hello
     
     - command: docker pull docker.io/jackgandhi/jack_apachedocker:latest
     
     - command: docker run -itd --name phpapplication -p 80:80 jackgandhi/jack_apachedocker:latest 
